---
project_name: customazed
builds:
  - goos: [linux, darwin, windows]
    goarch: [amd64]
archives:
  - name_template: '{{.ProjectName}}_{{if ne (printf "%.8s" .Version) "snapshot"}}v{{end}}{{.Version}}_{{.Os}}_{{.Arch}}'
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: 'snapshot-{{.ShortCommit}}'
