name: Test
on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Test Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go Test
        run: go test -v ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --snapshot
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist
  